"""rename item_art to item_img_url

Revision ID: e42e43c2e447
Revises: 3726f16a9bbd
Create Date: 2025-09-20 19:54:37.860656-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e42e43c2e447'
down_revision: Union[str, Sequence[str], None] = '3726f16a9bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_img_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_item_item_art'), table_name='item')
    op.create_index(op.f('ix_item_item_img_url'), 'item', ['item_img_url'], unique=False)
    op.drop_column('item', 'item_art')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_art', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_item_item_img_url'), table_name='item')
    op.create_index(op.f('ix_item_item_art'), 'item', ['item_art'], unique=False)
    op.drop_column('item', 'item_img_url')
    # ### end Alembic commands ###