"""add image url to catalog item model

Revision ID: 3726f16a9bbd
Revises: 04fa9474d949
Create Date: 2025-09-20 19:52:39.938799-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3726f16a9bbd'
down_revision: Union[str, Sequence[str], None] = '04fa9474d949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_art', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('item', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.create_index(op.f('ix_item_item_art'), 'item', ['item_art'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_art'), table_name='item')
    op.alter_column('item', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('item', 'item_art')
    # ### end Alembic commands ###