"""Add password management fields to users table

Revision ID: 040534f222c4
Revises: 25cb4eda2f69
Create Date: 2025-11-30 13:09:14.604762-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '040534f222c4'
down_revision: Union[str, Sequence[str], None] = '25cb4eda2f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password_reset_token_used', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('password_expires_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('user', sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_password_reset_token_hash'), 'user', ['password_reset_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token_hash'), table_name='user')
    op.drop_column('user', 'account_locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.drop_column('user', 'password_expires_at')
    op.drop_column('user', 'password_changed_at')
    op.drop_column('user', 'password_reset_token_used')
    op.drop_column('user', 'password_reset_token_expires')
    op.drop_column('user', 'password_reset_token_hash')
    # ### end Alembic commands ###