"""added catalog_event array to model

Revision ID: d0c03574f964
Revises: c3d335795135
Create Date: 2025-09-15 01:58:12.716168-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0c03574f964'
down_revision: Union[str, Sequence[str], None] = 'c3d335795135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogevent', sa.Column('catalog_ids', sa.ARRAY(sa.Integer()), nullable=True))
    op.alter_column('catalogevent', 'user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('catalogevent_catalog_id_fkey'), 'catalogevent', type_='foreignkey')
    op.drop_column('catalogevent', 'catalog_id')
    op.add_column('item', sa.Column('catalog_events', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'catalog_events')
    op.add_column('catalogevent', sa.Column('catalog_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('catalogevent_catalog_id_fkey'), 'catalogevent', 'item', ['catalog_id'], ['id'])
    op.alter_column('catalogevent', 'user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('catalogevent', 'catalog_ids')
    # ### end Alembic commands ###