"""rename check_out to checkout

Revision ID: 0c3e60615e4c
Revises: f4c002573cab
Create Date: 2025-09-16 23:08:21.585907-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c3e60615e4c'
down_revision: Union[str, Sequence[str], None] = 'f4c002573cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TYPE catalogactionmuseum ADD VALUE 'checkout'
        """
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###