"""add activation token fields to use

Revision ID: 6450e7668651
Revises: 4559893fa2ed
Create Date: 2025-11-29 12:12:43.945513-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6450e7668651'
down_revision: Union[str, Sequence[str], None] = '4559893fa2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activation_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('activation_token_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('activation_token_used', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_user_activation_token_hash'), 'user', ['activation_token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activation_token_hash'), table_name='user')
    op.drop_column('user', 'activation_token_used')
    op.drop_column('user', 'activation_token_expires')
    op.drop_column('user', 'activation_token_hash')
    # ### end Alembic commands ###