"""modified fine type for payment_intent

Revision ID: ed058beacc3d
Revises: ca421b357876
Create Date: 2025-11-07 14:46:05.935759-06:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed058beacc3d'
down_revision: Union[str, Sequence[str], None] = 'ca421b357876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('payment_intent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_fines_payment_intent_id'), 'fines', ['payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fines_payment_intent_id'), table_name='fines')
    op.drop_column('fines', 'payment_intent_id')
    # ### end Alembic commands ###