"""add days_late to fines table

Revision ID: 9c2790771588
Revises: aa6ba2c7bdfa
Create Date: 2025-10-27 14:24:06.799056-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c2790771588'
down_revision: Union[str, Sequence[str], None] = 'aa6ba2c7bdfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fines', sa.Column('days_late', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fines', 'days_late')
    # ### end Alembic commands ###