"""rename check_out to checkout in enum

Revision ID: 6d869d0895fb
Revises: 0c3e60615e4c
Create Date: 2025-09-17 00:42:44.045061-05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d869d0895fb'
down_revision: Union[str, Sequence[str], None] = '0c3e60615e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TYPE catalogactionsenum ADD VALUE 'checkout'
        """
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###